### ISSUE TITLE
Метод publishGame в классе GameStore не выдает исключение, если продублировать установку игры

### ISSUE THREAD

**Issue by VisYar** [ChechikJan/TeamDiplomChechikVisYar#6]
# Описание
Не реализована проверка метода publishGame в классе GameStore на выдачу исключения, если продублировать установку той же самой игры

# Локация дефекта
https://github.com/ChechikJan/TeamDiplomChechikVisYar/blob/6eac1149c411e3029beb7337d6f7389d3ca358ca/src/main/java/ru/netology/GameStore.java#L22-L26

# Шаги воспроизведения
1. Открыть [GameStoreTest](https://github.com/ChechikJan/TeamDiplomChechikVisYar/blob/master/src/test/java/ru/netology/GameStoreTest.java)
2. Вызвать метод publishGame для добавления игры в каталог
3. Добавить повторно ту же самую игру в каталог
4. Запустить тест shouldAddGameThatAlreadyExists
5. Посмотреть результат тестирования в консоли

*Ожидаемый результат:* метод выдал исключение, что игра есть в каталоге
*Фактический результат:* Ошибка в консоли AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![2022-08-09_23-32-28](https://user-images.githubusercontent.com/105548819/183755308-761b61c3-4ecb-4497-b55d-e9f0d355d05f.png)

# Окружение
* **Операционная система:** Windows 10 Pro Версия 21H2
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
*  **Java:** OpenJDK 11 Eclipse Temurin version 11.0.14

**Comment by ChechikJan** [comment]
В условиях мы не добавляем новые методы .а лишь редактируем старые по предложеным условиям

**Comment by ChechikJan** [comment]
тут мы должны ещё добавить метод поиска по названию и жанру.
