### ISSUE TITLE
Метод getMostPlayer в классе GameStore, если сыграно равное время возвращает одного игрока

### ISSUE THREAD

**Issue by VisYar** [ChechikJan/TeamDiplomChechikVisYar#8]
# Описание

# Локация дефекта
https://github.com/ChechikJan/TeamDiplomChechikVisYar/blob/6eac1149c411e3029beb7337d6f7389d3ca358ca/src/main/java/ru/netology/GameStore.java#L63-L65

# Шаги воспроизведения
1. Открыть [GameStoreTest](https://github.com/ChechikJan/TeamDiplomChechikVisYar/blob/master/src/test/java/ru/netology/GameStoreTest.java)
2. Вызвать метод addPlayTime("Ivan", 2);
3. Вызвать метод addPlayTime("Vita", 2);
4. Вызвать метод getMostPlayer
5. Запустить тест shouldGetMostPlayerIfPlayersAreEqual
6. Посмотреть результаты в консоли

*Ожидаемый результат:* null
*Фактический результат:* Ivan

# Скриншот
![2022-08-10_00-51-54](https://user-images.githubusercontent.com/105548819/183768357-8b1f5944-6774-4af4-bed8-7e7b28863468.png)

# Окружение
* **Операционная система:** Windows 10 Pro Версия 21H2
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
*  **Java:** OpenJDK 11 Eclipse Temurin version 11.0.14

**Comment by ChechikJan** [comment]
В данном тесте должно выдавать в ответе тогда уж двух игроков ,если игрока нет то null

**Comment by VisYar** [comment]
Исправление не требуется. Метод getMostPlayer в классе GameStore, если сыграно равное время возвращает одного игрока. Так и происходит.
![2022-08-11_13-18-06](https://user-images.githubusercontent.com/105548819/184112999-044f7caa-f74b-450c-ada9-6dc2a40cc523.png)

**Comment by VisYar** [comment]
Тест исправлен автором. Это не баг.
